### ISSUE TITLE
请教刷写 CC2510 遇到的问题

### ISSUE THREAD

**Issue by drianar** [fanhuanji/VUSION4.2BWR_GL340#1]
你好 fanhuanji，感谢你提供[引脚接线图](https://github.com/fanhuanji/VUSION4.2BWR_GL340/tree/main/PCB_Tool)，这非常有用。我按照这个图焊接了相同的线路，并连接到 CC Debugger 来烧录你的固件(cc.bin)。但使用 SmartRF Flash Programmer 刷入 cc.bin 时遇到 Could not open specified HEX file 错误(如图)。我用 srec_cat 或 arm-none-eabi-objcopy 把你的 bin 文件转换为 hex 文件再次刷入，这次显示
CC2510 - ID0211 Erase, program and verify OK。 但用你提供的 app-debug.apk -> MainEpdTool 无法写入图片到屏幕，并且 MainEpdTool  崩溃并停止响应。请问我是不是有什么地方遗漏或错误？谢谢。

![CC Debugger CC2510](https://github.com/user-attachments/assets/112a2822-6b19-4444-a9b8-792a7ef65fdf)

![SmartRF Flash Programmer, Could not open specified HEX file](https://github.com/user-attachments/assets/5a98c977-1b61-4135-b512-e7c0e04bd5d6)

邮箱
R21haWw6IGRpYW5hLnJvc3MxMjQ1Nw==

**Comment by fanhuanji** [comment]
请问，是app哪步操作时崩溃呢？能否提供下该app崩溃时的logcat输出呢？（通过adb获取）

**Comment by fanhuanji** [comment]
上传了app的工程到binary/MifareClassicTool-4.0.5-EPD.zip

如果有兴趣自行编译调试，可以试下（不过由于base的MifareClassTool版本及选择的AndroidAPI版本可能较老，工程首次配置时可能需要做些适配）

**Comment by drianar** [comment]
谢谢你的及时回复。我的操作是 TOOLS -> MainEpdTool ，然后把手机放到 PCB 上方 NFC 天线附近。  看到 MainEpdTool 窗口显示 “等待握手” "完成握手"，然后就崩溃了。我已经把 logcat 日志和操作过程放到 [Dropbox ](https://www.dropbox.com/scl/fo/946ar9hy7onxdj3muqs42/AIjT9RmlOJn4lz_htkAUz7Q?rlkey=wttsi73c6n60whjuh8nxv4mrj&e=3&st=zyd2lhyj&dl=0)。

谢谢分享源码，可惜我不是 Android 开发者。

**Comment by drianar** [comment]
另外，可以提供 hex  文件吗？我不确定我用 bin 转换的 hex 文件是否正确。

**Comment by oooooolr** [comment]
我也碰到了这个问题，用MainEpdTool靠近nfc后崩溃crash log:
time: 1739626243042
msg: java.lang.NullPointerException: Attempt to read from null array
stacktrace: java.lang.NullPointerException: Attempt to read from null array
	at de.syss.NfcTool.Activities.NfcEpdTool$2.run(NfcEpdTool.java:223)

**Comment by fanhuanji** [comment]
> 我也碰到了这个问题，用MainEpdTool靠近nfc后崩溃crash log: time: 1739626243042 msg: java.lang.NullPointerException: Attempt to read from null array stacktrace: java.lang.NullPointerException: Attempt to read from null array at de.syss.NfcTool.Activities.NfcEpdTool$2.run(NfcEpdTool.java:223)

根据log行号在那行位置看到了问题所在，请问是否有先点击界面上（默认）绿色的图片位置从相册选择图片？

之前传输的demo中，如果没有先选择好图片，就去触发NFC，会存在该处空引用问题，请试下先点击绿色位置正确选择图片后，再将手机靠近NFC天线。

**Comment by oooooolr** [comment]
> > 我也碰到了这个问题，用MainEpdTool靠近nfc后崩溃crash log: time: 1739626243042 msg: java.lang.NullPointerException: Attempt to read from null array stacktrace: java.lang.NullPointerException: Attempt to read from null array at de.syss.NfcTool.Activities.NfcEpdTool$2.run(NfcEpdTool.java:223)
> 
> 根据log行号在那行位置看到了问题所在，请问是否有先点击界面上（默认）绿色的图片位置从相册选择图片？
> 
> 之前传输的demo中，如果没有先选择好图片，就去触发NFC，会存在该处空引用问题，请试下先点击绿色位置正确选择图片后，再将手机靠近NFC天线。

选择图片之后，app不显示选中的图片。老早刚下载app第一次是会出图，后面几次用app都不出图。我换个手机再试试吧，谢谢回复

**Comment by fanhuanji** [comment]
> 谢谢你的及时回复。我的操作是 TOOLS -> MainEpdTool ，然后把手机放到 PCB 上方 NFC 天线附近。 看到 MainEpdTool 窗口显示 “等待握手” "完成握手"，然后就崩溃了。我已经把 logcat 日志和操作过程放到 [Dropbox ](https://www.dropbox.com/scl/fo/946ar9hy7onxdj3muqs42/AIjT9RmlOJn4lz_htkAUz7Q?rlkey=wttsi73c6n60whjuh8nxv4mrj&e=3&st=zyd2lhyj&dl=0)。
> 
> 谢谢分享源码，可惜我不是 Android 开发者。

很抱歉这么晚才回复，请看下[上面这条](https://github.com/fanhuanji/VUSION4.2BWR_GL340/issues/1#issuecomment-2661434248)，尝试下先点击绿色位置，选择图片后，再将手机靠近NFC天线，看是否不再出现崩溃。

一个比较可惜的事情是，其实我也不是安卓开发者，当初制作这个Android app是想测试下这个数据传输速率能达到多高，Android这方面我也不太了解，短期内这个Android App也不会再做更新。最初的版本中，我是使用Python脚本通过串口操作PN522进行图片传输的，该版本传输一张图片需要约60秒（如果有需要，我可以将该脚本重新调试好传上来）。

**Comment by fanhuanji** [comment]
对了，要确认目标设备是否正确运行，可以看蓝色LED是否点亮

另外，如果手上有空闲的ESP32开发板，可以使用该固件对墨水屏单板进行刷写，我是使用的（修改后的）该固件，对CC2510进行刷写。

[ESP_CC_Flasher](https://github.com/atc1441/ESP_CC_Flasher)

当时调试CC2510时手上没有cc debugger，只好基于上面这个开源项目修改了一个基于串口控制ESP32去单步调试CC2510的工具，如果只是刷写的话，上面这个开源项目应该足够使用了。

**Comment by oooooolr** [comment]
> 对了，要确认目标设备是否正确运行，可以看蓝色LED是否点亮
> 
> 另外，如果手上有空闲的ESP32开发板，可以使用该固件对墨水屏单板进行刷写，我是使用的（修改后的）该固件，对CC2510进行刷写。
> 
> [ESP_CC_Flasher](https://github.com/atc1441/ESP_CC_Flasher)
> 
> 当时调试CC2510时手上没有cc debugger，只好基于上面这个开源项目修改了一个基于串口控制ESP32去单步调试CC2510的工具，如果只是刷写的话，上面这个开源项目应该足够使用了。

刷好之后蓝灯亮的，那应该是app的问题了

**Comment by fanhuanji** [comment]
> > 对了，要确认目标设备是否正确运行，可以看蓝色LED是否点亮
> > 另外，如果手上有空闲的ESP32开发板，可以使用该固件对墨水屏单板进行刷写，我是使用的（修改后的）该固件，对CC2510进行刷写。
> > [ESP_CC_Flasher](https://github.com/atc1441/ESP_CC_Flasher)
> > 当时调试CC2510时手上没有cc debugger，只好基于上面这个开源项目修改了一个基于串口控制ESP32去单步调试CC2510的工具，如果只是刷写的话，上面这个开源项目应该足够使用了。
> 
> 刷好之后蓝灯亮的，那应该是app的问题了

App的话，尝试先点击界面绿色的部分选择图片再靠近试试（可能会需要文件/媒体操作权限什么的，不太确定当时使用的api是否需要，在Android 10上应该是没问题，后面更高版本的话好像权限管理上有变更，不知道能不能支持，不过app的工程前面也上传了，如果有兴趣，可以android studio编译调试下，包名修改过，与play商店原app不冲突），如果还不行，可能是不同设备NFC那边也有差异，这块可能就要再调试了。

**Comment by zfj1441** [comment]
1. 刷写工具推荐用这个[ESP32-CC-Tool-Pro ](https://github.com/z9m/ESP32-CC-Tool-Pro) 
2. 刷固件时先点‘擦除’，再点更新cc.bin固件
3. 刷写完断开多余的线，只保留（VCC、GND），此时主板蓝灯常亮
4. 大佬的APP需要较新的android手机，我android 7系统的手机，一靠近就提示“传输中断”，自己拿源码debug问AI改了一版本，供大家参考。

<img width="998" height="615" alt="Image" src="https://github.com/user-attachments/assets/86364aac-1576-42d7-886f-402cf5ed14d4" />
[Mifare Classic Tool_for_android7.zip](https://github.com/user-attachments/files/29387047/Mifare.Classic.Tool_for_android7.zip)
